services:
  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3001:3000" # Change the host port to 3001
    environment:
      # - REACT_APP_API_URL=http://backend:5000
      - REACT_APP_API_URL=http://localhost:5000 # Change the API URL to localhost
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend
    env_file:
      - ./client/.env

  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: cho2hand-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://anvnt96:asdqwe123@cluster0.bs2jhhq.mongodb.net/Cho2Hand
      - REDIS_URI=redis:6379
    volumes:
      - ./server:/app
      - /app/go/pkg/mod
    depends_on:
      - redis
    env_file:
      - ./server/.env
    networks:
      - app-network
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

networks:
  app-network:
    driver: bridge

volumes:
  redis_data: